'use client';
import {useEffect,useMemo,useRef,useState} from 'react';import './style.css';
const lv=['','🌱 مبتدئ','✏️ متوسط','🧠 متقدم'];
const shortName=name=>String(name||'').trim().split(/\s+/).filter(w=>!['بنت','بن','ابن'].includes(w)).slice(0,2).join(' ');
const colors=['#ffd666','#8fe0c1','#9db7ff','#f7a5b4','#c3a7ff','#8ed8ed','#ffc58b','#f6a6dc'];
export default function Home(){
 const [tab,setTab]=useState('lesson'),[students,setStudents]=useState([]),[qs,setQs]=useState([]),[idx,setIdx]=useState(0),[picked,setPicked]=useState(null),[msg,setMsg]=useState(''),[spin,setSpin]=useState(0),[busy,setBusy]=useState(false),[meta,setMeta]=useState({title:'',grade:'',subject:''});
 const [seconds,setSeconds]=useState(420),[running,setRunning]=useState(false),[duration,setDuration]=useState(420),[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0); const timer=useRef(null); const [usedStudents,setUsedStudents]=useState([]),[usedQuestions,setUsedQuestions]=useState([]),[history,setHistory]=useState([]),[review,setReview]=useState(false),[draftNames,setDraftNames]=useState([]),[answered,setAnswered]=useState(false);
 useEffect(()=>{try{setStudents(JSON.parse(localStorage.students||'[]'));setQs(JSON.parse(localStorage.qs||'[]'));setMeta(JSON.parse(localStorage.meta||'{"title":"","grade":"","subject":""}'));setHistory(JSON.parse(localStorage.hisatiHistory||'[]'));setUsedStudents(JSON.parse(localStorage.hisatiUsedStudents||'[]'));setUsedQuestions(JSON.parse(localStorage.hisatiUsedQuestions||'[]'))}catch{}},[]);
 useEffect(()=>{localStorage.students=JSON.stringify(students);localStorage.qs=JSON.stringify(qs);localStorage.meta=JSON.stringify(meta)},[students,qs,meta]);
 useEffect(()=>{localStorage.hisatiHistory=JSON.stringify(history);localStorage.hisatiUsedStudents=JSON.stringify(usedStudents);localStorage.hisatiUsedQuestions=JSON.stringify(usedQuestions)},[history,usedStudents,usedQuestions]);
 useEffect(()=>{if(running&&seconds>0){timer.current=setTimeout(()=>setSeconds(s=>s-1),1000)}else if(seconds===0){setRunning(false);setMsg('⏰ انتهى الوقت!')}return()=>clearTimeout(timer.current)},[running,seconds]);
 const q=qs[idx]; const wheel=useMemo(()=>students.length?`conic-gradient(${students.map((_,i)=>`${colors[i%colors.length]} ${i*360/students.length}deg ${(i+1)*360/students.length}deg`).join(',')})`:'#f0eef6',[students]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 function selectQuestion(student){let pool=qs.map((x,i)=>({...x,i})).filter(x=>!student||x.level===student.level);let fresh=pool.filter(x=>!usedQuestions.includes(x.i));if(!fresh.length){fresh=pool;setUsedQuestions([])}if(fresh.length){let next=fresh[Math.floor(Math.random()*fresh.length)];setIdx(next.i);setUsedQuestions(a=>[...a,next.i])}setAnswered(false)}
 function chooseStudent(){if(!students.length)return setTab('students');let available=students.map((s,i)=>({...s,studentId:i})).filter(s=>!usedStudents.includes(s.studentId));if(!available.length){available=students.map((s,i)=>({...s,studentId:i}));setUsedStudents([])}let s=available[Math.floor(Math.random()*available.length)];setSpin(x=>x+1800+Math.floor(Math.random()*360));setMsg('🎡 العجلة تدور…');setTimeout(()=>{setPicked(s);setUsedStudents(a=>[...a,s.studentId]);selectQuestion(s);setTab('lesson');setMsg(`🎯 دور ${shortName(s.name)}`)},3300)}
 function answer(i){if(!q||answered)return;setAnswered(true);let ok=i===q.correct;setAttempts(a=>a+1);if(ok)setCorrect(c=>c+1);setHistory(a=>[...a,{student:picked?.name||'بدون اسم',level:picked?.level||q.level,question:q.question,correct:ok}]);setMsg(ok?'⭐ أحسنتِ! إجابة صحيحة +1':'🌷 إجابة غير صحيحة، حاولي في السؤال القادم')}
 function nextQuestion(){if(!qs.length)return;selectQuestion(picked);setMsg('')}
 function newLesson(){if(!confirm('هل تريدين بدء حصة جديدة؟ سيتم مسح تقدم الحصة والأسئلة والطالبات المحفوظة على هذا الجهاز.'))return;setStudents([]);setQs([]);setMeta({title:'',grade:'',subject:''});setHistory([]);setUsedStudents([]);setUsedQuestions([]);setPicked(null);setIdx(0);setCorrect(0);setAttempts(0);setSeconds(duration);setRunning(false);setMsg('');setTab('questions')}
 async function generate(e){e.preventDefault();setBusy(true);setMsg('');let f=new FormData(e.currentTarget);try{let r=await fetch('/api/generate-questions',{method:'POST',body:f});let d=await r.json();if(!r.ok)throw Error(d.error);setQs(d.questions||[]);setUsedQuestions([]);setIdx(0);setMeta({title:f.get('title')||'',grade:f.get('grade')||'',subject:f.get('subject')||''});setTab('questions')}catch(x){alert(x.message)}finally{setBusy(false)}}
 async function compressImage(file){if(!file||!file.type?.startsWith('image/'))return file;return await new Promise((resolve,reject)=>{let img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{try{let max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;let ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(new File([b],'student-register.jpg',{type:'image/jpeg'})):resolve(file)},'image/jpeg',0.78)}catch(err){URL.revokeObjectURL(url);reject(err)}};img.onerror=()=>{URL.revokeObjectURL(url);resolve(file)};img.src=url})}
 async function extract(e){e.preventDefault();setBusy(true);try{let original=new FormData(e.currentTarget),file=original.get('image');if(!file||!file.size)throw Error('اختاري صورة سجل الطالبات أولًا.');let compressed=await compressImage(file),f=new FormData();f.append('image',compressed);let r=await fetch('/api/extract-students',{method:'POST',body:f});let raw=await r.text(),d;try{d=JSON.parse(raw)}catch{throw Error('تعذر الاتصال بخدمة قراءة السجل. أعيدي المحاولة.')}if(!r.ok)throw Error(d.error||'تعذر قراءة السجل.');let names=Array.isArray(d.students)?d.students.filter(Boolean):[];if(!names.length)throw Error('لم أجد أسماء واضحة. صوّري جزء الأسماء فقط بشكل أقرب.');setDraftNames(names.map(name=>({name:String(name),level:1})));setReview(true);alert(`تم استخراج ${names.length} طالبة. راجعي الأسماء ثم اضغطي اعتماد القائمة.`)}catch(x){alert(x.message||'تعذر قراءة السجل.')}finally{setBusy(false)}}
 return <main dir="rtl"><header><div className="brand"><div className="logo">💡</div><div><h1>حصتي الذكية</h1><p>مساعدتك الذكية لحصة أسهل وأجمل ✨</p></div></div><button className="iconBtn" onClick={()=>document.body.classList.toggle('night')}>☀️</button></header>
 <div className="hero"><div><span className="eyebrow">✨ الذكاء الاصطناعي معك</span><h2>ابدئي حصتك الذكية</h2><p>صوّري الدرس أو اكتبي عنوانه، وسنجهز لك الأسئلة بمستوياتها خلال لحظات.</p><div className="heroActions"><button className="coral" onClick={()=>setTab('questions')}>📷 رفع صور الدرس</button><button className="teal" onClick={()=>setTab('questions')}>📝 كتابة عنوان الدرس</button></div></div><div className="heroArt">🤖<small>أسئلة • تلميحات • مستويات</small></div></div>
 {tab==='lesson'&&<section className="lessonGrid"><div><div className="card top"><button className="gold" onClick={chooseStudent}>🎡 اختاري طالبة</button><button onClick={()=>setMsg(q?.hint||'لا يوجد تلميح')}>💡 تلميح</button><button onClick={()=>setMsg(q?`👁️ ${q.answer}`:'')}>👁️ الإجابة</button><button onClick={nextQuestion}>🔄 سؤال آخر</button><b>{picked?`${shortName(picked.name)} • ${lv[picked.level]}`:'الحصة'}</b></div><div className="card question">{q?<><span className="badge">{lv[q.level]}</span><h2>{q.question}</h2><div className="choices">{q.options.map((o,i)=><button key={i} onClick={()=>answer(i)}>{o}</button>)}</div><strong>{msg}</strong></>:<><div className="emptyIcon">📚</div><h2>الحصة غير مجهزة بعد</h2><p>ارفعي صور الدرس أو اكتبي عنوانه، والذكاء الاصطناعي يجهز الأسئلة.</p><button className="primary" onClick={()=>setTab('questions')}>✨ جهّزي درسي</button></>}</div></div><aside><div className="card timer"><div className="timerTitle">⏳ مؤقت النشاط</div><div className={seconds<=60?'clock urgent':'clock'}>{time}</div><div className="timerBtns"><button className="teal" onClick={()=>setRunning(r=>!r)}>{running?'⏸ إيقاف':'▶ تشغيل'}</button><button onClick={()=>{setRunning(false);setSeconds(duration)}}>↻ إعادة</button></div><div className="quickTimes">{[300,420,600].map(x=><button className={duration===x?'selected':''} key={x} onClick={()=>{setDuration(x);setSeconds(x);setRunning(false)}}>{x/60} د</button>)}</div></div><div className="card mini"><h3>📊 تقدم الحصة</h3><div className="stats"><span>الإجابات<b>{attempts}</b></span><span>الصحيحة<b>{correct}</b></span><span>الأسئلة<b>{qs.length}</b></span></div></div></aside></section>}
 {tab==='students'&&<section className="twoCols"><div className="card"><h2>📸 استيراد الطالبات من صورة</h2><p className="muted">صوّري سجل الطالبات وسيستخرج الذكاء الاصطناعي الأسماء تلقائيًا.</p><form onSubmit={extract}><label className="upload">📷 التقطي صورة أو اختاري صورة السجل<input name="image" type="file" accept="image/*"required/></label><button className="coral full" disabled={busy}>{busy?'جاري قراءة السجل…':'✨ استخرج الأسماء'}</button></form><button type="button" className="full" onClick={()=>setStudents(a=>[...a,{name:`طالبة ${a.length+1}`,level:1}])}>＋ إضافة طالبة يدويًا</button>{review&&<div className="reviewBox"><h3>🔎 مراجعة الأسماء قبل اعتمادها ({draftNames.length})</h3><p className="muted">عدّلي الأسماء أو المستوى قبل إضافتها للعجلة.</p><div className="names">{draftNames.map((s,i)=><div key={i}><input value={s.name} onChange={e=>setDraftNames(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><select value={s.level} onChange={e=>setDraftNames(a=>a.map((x,j)=>j===i?{...x,level:+e.target.value}:x))}><option value="1">مبتدئ</option><option value="2">متوسط</option><option value="3">متقدم</option></select><button onClick={()=>setDraftNames(a=>a.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className="teal full" onClick={()=>{setStudents(draftNames.filter(s=>s.name.trim()));setUsedStudents([]);setReview(false)}}>✓ اعتماد القائمة للعجلة</button><button className="full" onClick={()=>setReview(false)}>إلغاء</button></div>}<h3>الطالبات المعتمدات ({students.length})</h3><div className="names">{students.map((s,i)=><div key={i}><input value={s.name} onChange={e=>setStudents(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><select value={s.level} onChange={e=>setStudents(a=>a.map((x,j)=>j===i?{...x,level:+e.target.value}:x))}><option value="1">مبتدئ</option><option value="2">متوسط</option><option value="3">متقدم</option></select><button onClick={()=>setStudents(a=>a.filter((_,j)=>j!==i))}>×</button></div>)}</div></div><div className="card wheelCard"><h2>🎡 العجلة الدوارة</h2><p className="muted">اختاري طالبة عشوائيًا وابدئي بالسؤال المناسب لمستواها.</p><div className="wheelBox"><i></i><div className="wheel" style={{background:wheel,transform:`rotate(${spin}deg)`}}>{students.slice(0,12).map((s,i)=>{const a=(i+.5)*360/students.length;const r=38;const x=50+r*Math.sin(a*Math.PI/180);const y=50-r*Math.cos(a*Math.PI/180);return <label key={i} style={{left:`${x}%`,top:`${y}%`,transform:`translate(-50%,-50%) rotate(${a}deg)`}}>{shortName(s.name)}</label>})}<span>⭐</span></div></div><button className="coral full" onClick={chooseStudent}>🎡 دوّري العجلة</button></div></section>}
 {tab==='questions'&&<section className="twoCols"><div className="card"><h2>✨ جهّزي الدرس بالذكاء الاصطناعي</h2><p className="muted">يكفي عنوان الدرس، والأفضل إضافة صور الصفحات للحصول على أسئلة أدق.</p><form onSubmit={generate}><div className="grid"><input name="title" placeholder="اسم الدرس" defaultValue={meta.title} required/><select name="grade" defaultValue={meta.grade} required><option value="">اختاري الصف</option>{Array.from({length:10},(_,i)=><option key={i+1} value={`الصف ${i+1}`}>الصف {i+1}</option>)}</select><input name="subject" placeholder="المادة الدراسية" defaultValue={meta.subject} required/></div><textarea name="text" placeholder="اختياري: الصقي نص الدرس هنا"></textarea><label className="upload">📚 صوّري/ارفعي صفحات الدرس<input name="images" type="file" accept="image/* multiple/></label><select name="count" defaultValue="12"><option value="9">9 أسئلة</option><option value="12">12 سؤالًا</option><option value="15">15 سؤالًا</option></select><button className="teal full" disabled={busy}>{busy?'🤖 جاري تجهيز الحصة…':'✨ أنشئ بنك الأسئلة'}</button></form></div><div className="card"><h2>🧠 بنك الأسئلة <small>{qs.length}</small></h2>{!qs.length&&<div className="emptySmall">ستظهر الأسئلة هنا بعد تجهيز الدرس ✨</div>}<button type="button" className="full" onClick={()=>setQs(a=>[...a,{question:'سؤال جديد',options:['اختيار 1','اختيار 2','اختيار 3','اختيار 4'],correct:0,answer:'اختيار 1',hint:'',level:1}])}>＋ إضافة سؤال يدويًا</button>{qs.map((x,i)=><div className="qrow" key={i}><span>{lv[x.level]}</span><p>{x.question}</p><button onClick={()=>{let question=prompt('عدّلي نص السؤال:',x.question);if(question!==null)setQs(a=>a.map((z,j)=>j===i?{...z,question}:z))}}>تعديل</button><button onClick={()=>setQs(a=>a.filter((_,j)=>j!==i))}>حذف</button></div>)}</div></section>}
 {tab==='tools'&&<section><div className="card"><h2>📊 تقرير الحصة</h2><div className="metrics"><div>الطالبات<b>{students.length}</b></div><div>الأسئلة<b>{qs.length}</b></div><div>الإجابات الصحيحة<b>{correct}</b></div><div>الدرس<b>{meta.title||'—'}</b></div><div>المشاركات<b>{history.length}</b></div><div>نسبة الإجابات الصحيحة<b>{history.length?Math.round(100*history.filter(x=>x.correct).length/history.length):0}%</b></div><div>الطالبات المشاركات<b>{new Set(history.map(x=>x.student)).size}</b></div><div>الصف والمادة<b>{meta.grade||'—'} • {meta.subject||'—'}</b></div></div><h3>سجل المشاركة</h3><div className="reportRows">{history.map((x,i)=><p key={i}>{i+1}. {x.student} — {lv[x.level]} — {x.correct?'⭐ صحيحة':'تحتاج مراجعة'}</p>)}</div><button className="full" onClick={newLesson}>✨ بدء حصة جديدة</button><button className="primary full" onClick={()=>window.print()}>🖨️ طباعة / حفظ PDF</button></div></section>}
 <footer>إعداد وتصميم: أ. ثريا المعمري</footer><nav>{[['lesson','🎯 الحصة'],['students','👩‍🎓 الطالبات'],['questions','❓ الأسئلة'],['tools','📊 التقرير']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav></main>}
