'use client';
import {useEffect,useMemo,useRef,useState} from 'react';import './style.css';
const lv=['','🌱 مبتدئ','✏️ متوسط','🧠 متقدم'];
const colors=['#ffd666','#8fe0c1','#9db7ff','#f7a5b4','#c3a7ff','#8ed8ed','#ffc58b','#f6a6dc'];
export default function Home(){
 const [tab,setTab]=useState('lesson'),[students,setStudents]=useState([]),[qs,setQs]=useState([]),[idx,setIdx]=useState(0),[picked,setPicked]=useState(null),[msg,setMsg]=useState(''),[spin,setSpin]=useState(0),[busy,setBusy]=useState(false),[meta,setMeta]=useState({title:'',grade:'',subject:''});
 const [seconds,setSeconds]=useState(420),[running,setRunning]=useState(false),[duration,setDuration]=useState(420),[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0); const timer=useRef(null);
 useEffect(()=>{try{setStudents(JSON.parse(localStorage.students||'[]'));setQs(JSON.parse(localStorage.qs||'[]'));setMeta(JSON.parse(localStorage.meta||'{"title":"","grade":"","subject":""}'))}catch{}},[]);
 useEffect(()=>{localStorage.students=JSON.stringify(students);localStorage.qs=JSON.stringify(qs);localStorage.meta=JSON.stringify(meta)},[students,qs,meta]);
 useEffect(()=>{if(running&&seconds>0){timer.current=setTimeout(()=>setSeconds(s=>s-1),1000)}else if(seconds===0){setRunning(false);setMsg('⏰ انتهى الوقت!')}return()=>clearTimeout(timer.current)},[running,seconds]);
 const q=qs[idx]; const wheel=useMemo(()=>students.length?`conic-gradient(${students.map((_,i)=>`${colors[i%colors.length]} ${i*360/students.length}deg ${(i+1)*360/students.length}deg`).join(',')})`:'#f0eef6',[students]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 function chooseStudent(){if(!students.length)return setTab('students');let n=Math.floor(Math.random()*students.length);setSpin(x=>x+1800+Math.floor(Math.random()*360));setMsg('🎡 العجلة تدور…');setTimeout(()=>{let s=students[n];setPicked(s);let m=qs.map((x,i)=>({...x,i})).filter(x=>x.level===s.level);if(m.length)setIdx(m[Math.floor(Math.random()*m.length)].i);setTab('lesson');setMsg(`🎯 دور ${s.name}`)},3300)}
 function answer(i){if(!q)return;setAttempts(a=>a+1);if(i===q.correct){setCorrect(c=>c+1);setMsg('✨ أحسنتِ! إجابة صحيحة')}else setMsg('🌷 حاولي مرة أخرى')}
 function nextQuestion(){if(!qs.length)return;let pool=qs.map((x,i)=>({...x,i})).filter(x=>!picked||x.level===picked.level);let next=pool[Math.floor(Math.random()*pool.length)];if(next)setIdx(next.i);setMsg('')}
 async function compressImage(file,maxSide=1500,quality=.76){
  if(!file||!file.type?.startsWith('image/'))return file;
  const img=await new Promise((resolve,reject)=>{const im=new Image();const u=URL.createObjectURL(file);im.onload=()=>{URL.revokeObjectURL(u);resolve(im)};im.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('تعذر قراءة الصورة. جربي صورة أخرى.'))};im.src=u});
  let w=img.naturalWidth,h=img.naturalHeight,scale=Math.min(1,maxSide/Math.max(w,h));w=Math.max(1,Math.round(w*scale));h=Math.max(1,Math.round(h*scale));
  const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);
  const blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',quality));
  if(!blob)throw new Error('تعذر تجهيز الصورة.');
  return new File([blob],(file.name||'image').replace(/\.[^.]+$/, '')+'.jpg',{type:'image/jpeg'});
 }
 async function readApi(r){const text=await r.text();let d;try{d=JSON.parse(text)}catch{if(r.status===413)throw new Error('الصورة كبيرة جدًا. تم تحسين التطبيق لتصغير الصور تلقائيًا؛ أعيدي المحاولة بصورة واحدة واضحة.');throw new Error(`تعذر الاتصال بالخدمة (${r.status}). أعيدي المحاولة.`)}if(!r.ok)throw new Error(d?.error||'حدث خطأ في الخدمة.');return d}
 async function generate(e){e.preventDefault();setBusy(true);setMsg('');const raw=new FormData(e.currentTarget);try{const f=new FormData();for(const [k,v] of raw.entries())if(k!=='images')f.append(k,v);const imgs=raw.getAll('images').filter(x=>x?.size).slice(0,5);for(const img of imgs)f.append('images',await compressImage(img,1400,.72));let r=await fetch('/api/generate-questions',{method:'POST',body:f});let d=await readApi(r);setQs(d.questions||[]);setIdx(0);setMeta({title:f.get('title')||'',grade:f.get('grade')||'',subject:f.get('subject')||''});setTab('questions')}catch(x){alert(x.message||'تعذر تجهيز الدرس.')}finally{setBusy(false)}}
 async function extract(e){e.preventDefault();setBusy(true);const raw=new FormData(e.currentTarget);try{const image=raw.get('image');const f=new FormData();f.append('image',await compressImage(image,1600,.78));let r=await fetch('/api/extract-students',{method:'POST',body:f});let d=await readApi(r);if(!d.students?.length)throw new Error('لم أتمكن من العثور على أسماء واضحة في الصورة.');setStudents(d.students.map(name=>({name,level:1})));setMsg(`تم استخراج ${d.students.length} اسمًا بنجاح ✨`)}catch(x){alert(x.message||'تعذر قراءة السجل.')}finally{setBusy(false)}}
 return <main dir="rtl"><header><div className="brand"><div className="logo">💡</div><div><h1>حصتي الذكية</h1><p>مساعدتك الذكية لحصة أسهل وأجمل ✨</p></div></div><button className="iconBtn" onClick={()=>document.body.classList.toggle('night')}>☀️</button></header>
 <div className="hero"><div><span className="eyebrow">✨ الذكاء الاصطناعي معك</span><h2>ابدئي حصتك الذكية</h2><p>صوّري الدرس أو اكتبي عنوانه، وسنجهز لك الأسئلة بمستوياتها خلال لحظات.</p><div className="heroActions"><button className="coral" onClick={()=>setTab('questions')}>📷 رفع صور الدرس</button><button className="teal" onClick={()=>setTab('questions')}>📝 كتابة عنوان الدرس</button></div></div><div className="heroArt">🤖<small>أسئلة • تلميحات • مستويات</small></div></div>
 {tab==='lesson'&&<section className="lessonGrid"><div><div className="card top"><button className="gold" onClick={chooseStudent}>🎡 اختاري طالبة</button><button onClick={()=>setMsg(q?.hint||'لا يوجد تلميح')}>💡 تلميح</button><button onClick={()=>setMsg(q?`👁️ ${q.answer}`:'')}>👁️ الإجابة</button><button onClick={nextQuestion}>🔄 سؤال آخر</button><b>{picked?`${picked.name} • ${lv[picked.level]}`:'الحصة'}</b></div><div className="card question">{q?<><span className="badge">{lv[q.level]}</span><h2>{q.question}</h2><div className="choices">{q.options.map((o,i)=><button key={i} onClick={()=>answer(i)}>{o}</button>)}</div><strong>{msg}</strong></>:<><div className="emptyIcon">📚</div><h2>الحصة غير مجهزة بعد</h2><p>ارفعي صور الدرس أو اكتبي عنوانه، والذكاء الاصطناعي يجهز الأسئلة.</p><button className="primary" onClick={()=>setTab('questions')}>✨ جهّزي درسي</button></>}</div></div><aside><div className="card timer"><div className="timerTitle">⏳ مؤقت النشاط</div><div className={seconds<=60?'clock urgent':'clock'}>{time}</div><div className="timerBtns"><button className="teal" onClick={()=>setRunning(r=>!r)}>{running?'⏸ إيقاف':'▶ تشغيل'}</button><button onClick={()=>{setRunning(false);setSeconds(duration)}}>↻ إعادة</button></div><div className="quickTimes">{[300,420,600].map(x=><button className={duration===x?'selected':''} key={x} onClick={()=>{setDuration(x);setSeconds(x);setRunning(false)}}>{x/60} د</button>)}</div></div><div className="card mini"><h3>📊 تقدم الحصة</h3><div className="stats"><span>الإجابات<b>{attempts}</b></span><span>الصحيحة<b>{correct}</b></span><span>الأسئلة<b>{qs.length}</b></span></div></div></aside></section>}
 {tab==='students'&&<section className="twoCols"><div className="card"><h2>📸 استيراد الطالبات من صورة</h2><p className="muted">صوّري سجل الطالبات وسيستخرج الذكاء الاصطناعي الأسماء تلقائيًا.</p><form onSubmit={extract}><label className="upload">📷 التقطي صورة أو اختاري صورة السجل<input name="image" type="file" accept="image/*" capture="environment" required/></label><button className="coral full" disabled={busy}>{busy?'جاري قراءة السجل…':'✨ استخرج الأسماء'}</button></form><button type="button" className="full" onClick={()=>setStudents(a=>[...a,{name:`طالبة ${a.length+1}`,level:1}])}>＋ إضافة طالبة يدويًا</button><div className="names">{students.map((s,i)=><div key={i}><input value={s.name} onChange={e=>setStudents(a=>a.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><select value={s.level} onChange={e=>setStudents(a=>a.map((x,j)=>j===i?{...x,level:+e.target.value}:x))}><option value="1">مبتدئ</option><option value="2">متوسط</option><option value="3">متقدم</option></select><button onClick={()=>setStudents(a=>a.filter((_,j)=>j!==i))}>×</button></div>)}</div></div><div className="card wheelCard"><h2>🎡 العجلة الدوارة</h2><p className="muted">اختاري طالبة عشوائيًا وابدئي بالسؤال المناسب لمستواها.</p><div className="wheelBox"><i></i><div className="wheel" style={{background:wheel,transform:`rotate(${spin}deg)`}}>{students.slice(0,12).map((s,i)=>{const a=(i+.5)*360/students.length;const r=38;const x=50+r*Math.sin(a*Math.PI/180);const y=50-r*Math.cos(a*Math.PI/180);return <label key={i} style={{left:`${x}%`,top:`${y}%`,transform:`translate(-50%,-50%) rotate(${a}deg)`}}>{s.name}</label>})}<span>⭐</span></div></div><button className="coral full" onClick={chooseStudent}>🎡 دوّري العجلة</button></div></section>}
 {tab==='questions'&&<section className="twoCols"><div className="card"><h2>✨ جهّزي الدرس بالذكاء الاصطناعي</h2><p className="muted">يكفي عنوان الدرس، والأفضل إضافة صور الصفحات للحصول على أسئلة أدق.</p><form onSubmit={generate}><div className="grid"><input name="title" placeholder="اسم الدرس" defaultValue={meta.title} required/><input name="grade" placeholder="الصف" defaultValue={meta.grade}/><input name="subject" placeholder="المادة" defaultValue={meta.subject}/></div><textarea name="text" placeholder="اختياري: الصقي نص الدرس هنا"></textarea><label className="upload">📚 صوّري/ارفعي صفحات الدرس<input name="images" type="file" accept="image/*" capture="environment" multiple/></label><select name="count" defaultValue="12"><option value="9">9 أسئلة</option><option value="12">12 سؤالًا</option><option value="15">15 سؤالًا</option></select><button className="teal full" disabled={busy}>{busy?'🤖 جاري تجهيز الحصة…':'✨ أنشئ بنك الأسئلة'}</button></form></div><div className="card"><h2>🧠 بنك الأسئلة <small>{qs.length}</small></h2>{!qs.length&&<div className="emptySmall">ستظهر الأسئلة هنا بعد تجهيز الدرس ✨</div>}{qs.map((x,i)=><div className="qrow" key={i}><span>{lv[x.level]}</span><p>{x.question}</p><button onClick={()=>setQs(a=>a.filter((_,j)=>j!==i))}>حذف</button></div>)}</div></section>}
 {tab==='tools'&&<section><div className="card"><h2>📊 تقرير الحصة</h2><div className="metrics"><div>الطالبات<b>{students.length}</b></div><div>الأسئلة<b>{qs.length}</b></div><div>الإجابات الصحيحة<b>{correct}</b></div><div>الدرس<b>{meta.title||'—'}</b></div></div><button className="primary full" onClick={()=>window.print()}>🖨️ طباعة / حفظ PDF</button></div></section>}
 <footer>إعداد وتصميم: أ. ثريا المعمري</footer><nav>{[['lesson','🎯 الحصة'],['students','👩‍🎓 الطالبات'],['questions','❓ الأسئلة'],['tools','📊 التقرير']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav></main>}
